# Generated by Django 6.0.2 on 2026-03-04 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], max_length=50, unique=True)),
                ('can_add_patient', models.BooleanField(default=True)),
                ('can_edit_patient', models.BooleanField(default=True)),
                ('can_delete_patient', models.BooleanField(default=False)),
                ('can_add_doctor', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_view_audit_logs', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
            ],
        ),
    ]
