# Generated by Django 6.0.2 on 2026-03-06 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_id', models.CharField(default='GLOBAL', max_length=50, unique=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('password_policy_strictness', models.CharField(default='Medium', max_length=50)),
            ],
        ),
    ]
