# Generated by Django 6.0.2 on 2026-03-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_securitysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('CONSULTANT', 'Consultant'), ('ASSISTANT', 'Assistant')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('CONSULTANT', 'Consultant'), ('ASSISTANT', 'Assistant')], default='DOCTOR', max_length=20),
        ),
    ]
