# Generated by Django 6.0.2 on 2026-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_rolepermission_role_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("ASSISTANT", "Assistant"),
                    ("INTERN", "Intern"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("ASSISTANT", "Assistant"),
                    ("INTERN", "Intern"),
                ],
                default="DOCTOR",
                max_length=20,
            ),
        ),
    ]
