# Generated by Django 6.0.2 on 2026-03-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_rolepermission_role_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, default="None", null=True),
        ),
    ]
