# Generated by Django 6.0.2 on 2026-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_patient_allergies"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermission",
            name="can_prescribe_drugs",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="can_use_ai",
            field=models.BooleanField(default=True),
        ),
    ]
