# Generated by Django 6.0.2 on 2026-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rolepermission_can_prescribe_drugs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermission",
            name="can_view_patients",
            field=models.BooleanField(default=True),
        ),
    ]
