# Generated by Django 6.0.2 on 2026-03-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_rolepermission_can_view_patients"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitysetting",
            name="aggressive_path_detection",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="securitysetting",
            name="dicom_mirror",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="securitysetting",
            name="ultra_dark_mode",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="securitysetting",
            name="vital_overlay",
            field=models.BooleanField(default=False),
        ),
    ]
