# Generated by Django 6.0.2 on 2026-03-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_securitysetting_aggressive_path_detection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="last_visit_date",
            field=models.CharField(blank=True, default="N/A", max_length=50, null=True),
        ),
    ]
